### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Madji** [anewusername/mxpp#8]
python3 -m mxpp.main
INFO     XMPP Logged in!
ERROR    xmpp_presence_available: JID admin@server.pu NOT IN ROSTER!?
ERROR    Error processing event handler: <bound method BridgeBot.xmpp_presence_available of <__main__.BridgeBot object at 0x7f3b71b9c630>>
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.0/lib/python3.6/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1708, in _event_runner
    func(*args)
  File "/root/bridge/mxpp/mxpp/main.py", line 464, in xmpp_presence_available
    name = self.xmpp.jid_nick_map[jid]
KeyError: 'admin@server.pu'

all contacts added to the roster. both. correctly displayed status. where to dig? where I went wrong. thank you

**Comment by anewusername** [comment]
This happens when a server sends you presence info and messages from people who don't show up on the roster that the server sends you.

I see this occasionally for a few of my contacts, but I still haven't figured out what to do to reliably get the full roster with SleekXMPP.

I've attempted to mitigate the bug now with a few changes to how I treat the nickname lookup, but I'd like to fix the underlying issue eventually.

**Comment by Madji** [comment]
thanks.I understand
